### PR TITLE
Create YashPage.js

### PR DESCRIPTION
**Pull request by ysthakur**
Made a page for myself

### CODE REVIEW

**Comment by iwotastic** [comment]
Hi, it seems that you haven't added yourself to the `App.js` file, so your page wouldn't be visible. If you do that, commit, and push; I can merge your changes.

**Comment by ysthakur** [comment]
Whoops, fixed now

**Comment by iwotastic** [comment]
Sorry it took me a while to get back to you, there is one spot you missed in the `App.js`, which would make navigating to your page fail. You'll want to add a line like line 71, which navigates to your page.

**Comment by ysthakur** [comment]
Oh sorry, hopefully it's fine now.

**Pull request merged**
